development:
 #Sqlite Settings
  #adapter: sqlite3
  #database: abtacular_dev
  #pool: 5
  #timeout: 5000

  # Postgresql Settings
  adapter: postgresql
  database: printworks_dev
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_development
  # username: root
  # password:
  # pool: 5
  
test: &test
  # Sqlite Settings
  #adapter: sqlite3
  #database: db/printworks_test
  #pool: 5
  #timeout: 5000

  # Postgresql Settings
  adapter: postgresql
  database: printworks_test
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_test
  # username: root
  # password:
  # pool: 5
  
staging:
  # Postgres Settings
  adapter: postgresql
  database: printworks_staging
  username: libai
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_staging
  # username: root
  # password:
  # pool: 5
  
production:
  # Postgres Settings
  adapter: postgresql
  database: printworks_production
  username: libai
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_production
  # username: root
  # password:
  # pool: 5

cucumber:
  <<: *test
